server:
  port: 8763

spring:
  application:
    name: app-that-needs-name

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceurl:
    defaultzone: ${EUREKA_URI:http://localhost:8761/eureka}
