server:
  port: 8762

spring:
  application:
    name: gateway

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceurl:
    defaultzone: ${EUREKA_URI:http://localhost:8761/eureka}

zuul:
  ignoredServices: '*'
  routes:
    app-that-needs-name: /api/**